// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dotnet_services_viewer.Infrastructure;

#nullable disable

namespace dotnet_services_viewer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260415145542_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.6");

            modelBuilder.Entity("dotnet_services_viewer.Domain.Container", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("CpuThreshold")
                        .HasColumnType("REAL");

                    b.Property<double>("CurrentCpuUsage")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("NodeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NodeId");

                    b.ToTable("Containers");
                });

            modelBuilder.Entity("dotnet_services_viewer.Domain.Node", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Hostname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Nodes");
                });

            modelBuilder.Entity("dotnet_services_viewer.Domain.Container", b =>
                {
                    b.HasOne("dotnet_services_viewer.Domain.Node", null)
                        .WithMany("Containers")
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("dotnet_services_viewer.Domain.Node", b =>
                {
                    b.OwnsOne("dotnet_services_viewer.Domain.SshConfig", "SshConfig", b1 =>
                        {
                            b1.Property<int>("NodeId")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Port")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("PrivateKeyPath")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Username")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("NodeId");

                            b1.ToTable("Nodes");

                            b1.WithOwner()
                                .HasForeignKey("NodeId");
                        });

                    b.Navigation("SshConfig")
                        .IsRequired();
                });

            modelBuilder.Entity("dotnet_services_viewer.Domain.Node", b =>
                {
                    b.Navigation("Containers");
                });
#pragma warning restore 612, 618
        }
    }
}
